### ISSUE TITLE
empty jgmenu

### ISSUE THREAD

**Issue by eoli3n** [johanmalm/jgmenu#71]
Just installed jgmenu, everything worked well, then, aftere removing some .desktop files, i have a python error when building the menu

```
❯ jgmenu_run pmenu
jgmenu,^tag(pmenu)
@rect,,14,14,174,40,3,left,top,#aaaaaa 15,#000000 0,content
@search,,14,14,174,40,3,left,top,#aaaaaa 90,#222222 3,Type to search...
^sep()

Traceback (most recent call last):
  File "/usr/lib/jgmenu/jgmenu-pmenu.py", line 503, in <module>
    main()
  File "/usr/lib/jgmenu/jgmenu-pmenu.py", line 500, in main
    create_menu(append_file, prepend_file)
  File "/usr/lib/jgmenu/jgmenu-pmenu.py", line 437, in create_menu
    print(category["Name_markup"] + ",^checkout(" + category["Name"] + ")," + icon)
KeyError: 'Name_markup'
```

Here ``.config/jgmenu/jgmenurc``
```
menu_padding_top    = 63
sub_padding_top     = 5
menu_width          = 210
menu_height_min     = 100
menu_height_max     = 800
menu_margin_x       = 0
menu_margin_y       = 20
```
Already tried to run ``update-desktop-database``, but nothing changed

**Comment by eoli3n** [comment]
To solve this
```
pacman -S archlinux-xdg-menu
update-menus
```

**Comment by johanmalm** [comment]
Hi. Appreciate you reporting this. I’m not sure what caused the issue, but I don’t like the look of it. pmenu should handle it better.
You shouldn’t need to install archlinux-xdg-menu and
update-menus.
Would you be up for helping me fault find if I suggest some things to try?
Can you get to a state where you can replicate the big again?
