### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/tn/.config/jgmenu/jgmenurc'

### ISSUE THREAD

**Issue by theone29** [johanmalm/jgmenu#85]
Hi, I'm getting an error when running jgmenu init. I running i3 on the latest Arch and kernel 5. Please assist. Great program btw.

[tn@ALZ400 ~]$ jgmenu init
info: creating config file 'jgmenurc'
Traceback (most recent call last):
  File "/usr/lib/jgmenu/jgmenu-config.py", line 182, in <module>
    main()
  File "/usr/lib/jgmenu/jgmenu-config.py", line 175, in main
    create(args.file)
  File "/usr/lib/jgmenu/jgmenu-config.py", line 155, in create
    with open(conf_filename, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tn/.config/jgmenu/jgmenurc'
Run 'jgmenu init -h' for usage message
Run 'jgmenu init -i' to enter interactive mode
[tn@ALZ400 ~]$ killall jgmenu
[tn@ALZ400 ~]$ jgmenu init
info: creating config file 'jgmenurc'
Traceback (most recent call last):
  File "/usr/lib/jgmenu/jgmenu-config.py", line 182, in <module>
    main()
  File "/usr/lib/jgmenu/jgmenu-config.py", line 175, in main
    create(args.file)
  File "/usr/lib/jgmenu/jgmenu-config.py", line 155, in create
    with open(conf_filename, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/tn/.config/jgmenu/jgmenurc'
Run 'jgmenu init -h' for usage message
Run 'jgmenu init -i' to enter interactive mode

**Comment by theone29** [comment]
weird.. I ran jgmenu init again and it's creating the file. TY.

**Comment by theone29** [comment]
weird.. I ran jgmenu init again and it's creating the file. TY.

**Comment by johanmalm** [comment]
Thanks for feedback. I had forgotten a `mkdir -p` for the directory that the config file into. Now fixed.
